version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message: 
      prefix: "Dependabot (github actions): "
    groups: 
      gh-actions:
        applies-to: version-updates
        patterns:
          - "*"
      gh-actions-security:
        applies-to: security-updates
        patterns:
          - "*"

  - package-ecosystem: "terraform"
    directory: "/terraform"
    schedule:
      interval: "weekly"
    commit-message: 
      prefix: "Dependabot (terraform): "
    groups: 
      terraform:
        applies-to: version-updates
        patterns:
          - "*"
      terraform-security:
        applies-to: security-updates
        patterns:
          - "*"